// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTb8HoZH4truFjaH0amyAXGx6Yj9eOQfs',
    appId: '1:876669351530:web:8be691dc130f177d7dbc13',
    messagingSenderId: '876669351530',
    projectId: 'chatapp-77879',
    authDomain: 'chatapp-77879.firebaseapp.com',
    storageBucket: 'chatapp-77879.appspot.com',
    measurementId: 'G-06HZWX62VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOOfX1HHUTEjRucY3Gf4cDsBxdfrsQl4E',
    appId: '1:876669351530:android:785189e6d0d34d3b7dbc13',
    messagingSenderId: '876669351530',
    projectId: 'chatapp-77879',
    storageBucket: 'chatapp-77879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYX0xT09VA-KvY6rYWrteL_M8XnUYRPSc',
    appId: '1:876669351530:ios:a1b2cbd9a849f6857dbc13',
    messagingSenderId: '876669351530',
    projectId: 'chatapp-77879',
    storageBucket: 'chatapp-77879.appspot.com',
    androidClientId: '876669351530-b3g1komfcuvugj1bo7c5ncf5p34tbm01.apps.googleusercontent.com',
    iosClientId: '876669351530-bl9blbk05d8jq197idqf381drsc0a47p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYX0xT09VA-KvY6rYWrteL_M8XnUYRPSc',
    appId: '1:876669351530:ios:a1b2cbd9a849f6857dbc13',
    messagingSenderId: '876669351530',
    projectId: 'chatapp-77879',
    storageBucket: 'chatapp-77879.appspot.com',
    androidClientId: '876669351530-b3g1komfcuvugj1bo7c5ncf5p34tbm01.apps.googleusercontent.com',
    iosClientId: '876669351530-bl9blbk05d8jq197idqf381drsc0a47p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTb8HoZH4truFjaH0amyAXGx6Yj9eOQfs',
    appId: '1:876669351530:web:4cbd34c42797b5a97dbc13',
    messagingSenderId: '876669351530',
    projectId: 'chatapp-77879',
    authDomain: 'chatapp-77879.firebaseapp.com',
    storageBucket: 'chatapp-77879.appspot.com',
    measurementId: 'G-FCSYB5C06L',
  );
}
